repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: detect-private-key
# flake doesn't work with exclude=migrations, find out a way to fix that
#-   repo: https://github.com/pycqa/flake8
#    rev: 3.8.4
#    hooks:
#    -   id: flake8
#        args:
#        -    --exclude=migrations,.git,__pycache__,settings.py,venv,0001_initial.py
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        args:
        -    --disable=C0114,E0401,C0115,R0903,C0301,C0116,C0103,R0201
        -    --output-format=colorized
        -    --score=no
        -    --ignore=manage.py
        -    --ignore-patterns=test
