repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: detect-private-key
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args:
        -    --extend-exclude
        -    settings.py
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        args:
        -    --disable=C0114,E0401,C0115,R0903
        -    --output-format=colorized
        -    --score=no
        -    --ignore=manage.py
        -    --ignore-patterns=test
